spring:
  application:
    name: fmi-enroll-prototype-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}

# server configuration
server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
  error:
    include-message: always
    include-binding-errors: always

# base logging config
logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    fmi.enroll: ${APP_LOG_LEVEL:DEBUG}
    org.hibernate.SQL: ${HIBERNATE_LOG_LEVEL:DEBUG}
    org.hibernate.type.descriptor.sql.BasicBinder: ${SQL_BIND_LOG_LEVEL:TRACE}